version: '0.1'
name: 'sensors-data_manager'

services:

  sensors-api:
    container_name: sensors-flask_app
    build:
      context: ./repositories/SensorsAPI-SmartInstall

    volumes:
      - type: bind
        source: /home/user/docker_volumes/sensors-api_instance
        target: /app/instance/

    ports:
      - "2020:2020"
    
    restart: always


  api-mqtt:
    container_name: sensors-api_mqtt
    build:
      context: ./repositories/Sensors-SmartInstall/MQTT/Python/mqtt_api_bridge
    
    volumes:
      - type: bind
        source: /home/user/docker_volumes/mqtt_api_bridge
        target: /app/instance/

    restart: always

  
  mqtt-broker:
    container_name: sensors-mqtt_broker
    image: eclipse-mosquitto:latest

    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - type: bind
        source: /home/user/docker_volumes/mosquitto
        target: /mosquitto/config/

    restart: always